# How to use DataFrame
https://pythonhow.com/accessing-dataframe-columns-rows-and-cells/

```python
df2 = pd.read_csv('somefile.csv')
df2.loc[startrow:endrow, startcolumn:endcolumn]
```

In [15]:
import pandas as pd
content = pd.read_csv("~/git/Jupyter/csv/desp-out-2020.csv")
c2 = content.loc[:, "Valor": "Categoria"]
c2[["Valor", "Categoria"]]

       Valor     Categoria
0      29,50          Casa
1      92,98         Lazer
2      19,75        Lanche
3      20,00       Reparos
4     326,87   Aprendizado
5     139,99          Casa
6   1.520,00   Habilitação
7   1.300,00          Casa
8      45,00  Instrumentos
9      84,00          Pets
10     29,00  Instrumentos
11     50,00  Contribuição
12    101,90        Lanche
13     29,99     Vestuário
14     31,94         Lazer
15     25,65         Lazer
16    100,00       Reparos
17     48,30          Casa
18     59,99     Presentes
19     67,00        Lanche
20    148,45          Casa
21    149,90          Casa
22     89,90  Contribuição
23     25,00       Reparos
24    370,00       Reparos
25     44,00         Lazer
26    380,00  Contribuição
27     32,00        Lanche
28    436,31       Crédito
29     11,00        Lanche
30    214,84          Casa
31     61,20        Lanche
32     14,00        Lanche
33     30,00  Contribuição
34    369,99       Crédito
35    501,71       Crédito
36     14,50     Presentes
37     35,00          Pets
38     87,00        Lanche
39     50,00        Viagem
40     77,31        Viagem
41     33,75        Viagem
42    100,51        Viagem
43     86,00        Viagem
44     51,99     Telefonia
45     13,25         Taxas
46     22,25        Lanche
47    152,00         Lazer